services:
  - type: web
    name: movieshub
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn movieshub.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movieshub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: movies-hub-6dhp.onrender.com
      - key: BASE_URL
        value: https://movies-hub-6dhp.onrender.com   # <-- add this
      # ... other keys (AWS, TELEGRAM_BOT_TOKEN, MAIN_CHANNEL_ID, TELEGRAM_ADMIN_IDS)
    databases:
      - name: movieshub-db
        databaseName: movieshub
        user: movieshub