"""
Django settings for movieshub project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import re
import logging
from dotenv import load_dotenv
import dj_database_url

logger = logging.getLogger(__name__)

# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load .env for local development
load_dotenv(BASE_DIR / ".env")
logger.debug("Loaded environment from %s", BASE_DIR / ".env")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# --------------------------------------------------
# SECURITY
# --------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY and not DEBUG:
    raise ValueError("SECRET_KEY environment variable is required.")

if not SECRET_KEY:
    SECRET_KEY = "django-insecure-dev-only-key"

ALLOWED_HOSTS = [
    host.strip()
    for host in (
        [
            "localhost",
            "127.0.0.1",
            "movies-hub-6dhp.onrender.com",
        ]
        + os.getenv("ALLOWED_HOSTS", "").split(",")
    )
    if host.strip()
]

# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",

    # Third Party
    'storages',

    # Local Apps
    'coremovieshub',
]

# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'movieshub.urls'

# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movieshub.wsgi.application'

# --------------------------------------------------
# DATABASE SETUP
# --------------------------------------------------
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,
            ssl_require=True,
        )
    }
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "require",
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# --------------------------------------------------
# CUSTOM USER MODEL
# --------------------------------------------------
AUTH_USER_MODEL = 'coremovieshub.CustomUser'

# --------------------------------------------------
# AUTHENTICATION
# --------------------------------------------------
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --------------------------------------------------
# AWS S3 CONFIGURATION
# --------------------------------------------------
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-north-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'

AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False

AWS_S3_CUSTOM_DOMAIN = (
    f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    if AWS_STORAGE_BUCKET_NAME
    else None
)

# --------------------------------------------------
# MEDIA FILES (VIDEOS, THUMBNAILS, ETC.)
# --------------------------------------------------
MEDIA_URL = (
    f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    if AWS_STORAGE_BUCKET_NAME
    else "/media/"
)

# --------------------------------------------------
# DJANGO 6 STORAGE SETTINGS
# --------------------------------------------------
if AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "default_acl": None,
                "querystring_auth": False,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------
# CACHE
# --------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "movieshub-cache",
    }
}

# --------------------------------------------------
# TELEGRAM BOT
# --------------------------------------------------
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
if not DEBUG and not TELEGRAM_BOT_TOKEN:
    raise ValueError("TELEGRAM_BOT_TOKEN environment variable is required.")

TELEGRAM_CHANNEL_ID = os.getenv("TELEGRAM_CHANNEL_ID", "").strip()
if TELEGRAM_CHANNEL_ID:
    try:
        TELEGRAM_CHANNEL_ID = int(TELEGRAM_CHANNEL_ID)
    except ValueError:
        raise ValueError("TELEGRAM_CHANNEL_ID must be a valid Telegram chat ID.")
else:
    TELEGRAM_CHANNEL_ID = None

TELEGRAM_BOT_USERNAME = os.getenv(
    "TELEGRAM_BOT_USERNAME",
    "jaymovieshubbot"
)

TELEGRAM_ADMIN_IDS = [
    int(x)
    for x in os.getenv("TELEGRAM_ADMIN_IDS", "").split(",")
    if x.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "https://movies-hub-6dhp.onrender.com",
]

TELEGRAM_SECRET = os.getenv("TELEGRAM_SECRET", "")
if not DEBUG and not TELEGRAM_SECRET:
    raise ValueError("TELEGRAM_SECRET environment variable is required.")

# Render Proxy Support
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --------------------------------------------------
# BASE URL
# --------------------------------------------------
BASE_URL = os.getenv("BASE_URL", "https://movies-hub-6dhp.onrender.com")

# Cookie Security
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
CSRF_COOKIE_HTTPONLY = False
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# --------------------------------------------------
# MAIN CHANNEL
# --------------------------------------------------
MAIN_CHANNEL_ID = os.getenv("MAIN_CHANNEL_ID", "").strip()
if MAIN_CHANNEL_ID:
    try:
        MAIN_CHANNEL_ID = int(MAIN_CHANNEL_ID)
    except ValueError:
        raise ValueError(
            "MAIN_CHANNEL_ID must be a valid Telegram chat ID (example: -1001234567890)."
        )
else:
    if DEBUG:
        MAIN_CHANNEL_ID = None
    else:
        logger.warning("MAIN_CHANNEL_ID is not configured.")
        MAIN_CHANNEL_ID = None

# --------------------------------------------------
# Security Improvements
# --------------------------------------------------
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
X_FRAME_OPTIONS = "DENY"

# --------------------------------------------------
# EMAIL CONFIGURATION
# --------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_TIMEOUT = 30
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@movieshub.com"

# ==================================================
# EXTERNAL API CONFIGURATION
# ==================================================

# ---- TMDB ----
TMDB_API_KEY = os.getenv("TMDB_API_KEY", "").strip()

# Validate and log
if not TMDB_API_KEY:
    if DEBUG:
        logger.warning("TMDB_API_KEY not found. Metadata lookup is disabled.")
    else:
        raise ValueError("TMDB_API_KEY environment variable is required.")
else:
    # Basic format check (32 hex chars)
    if not re.fullmatch(r"[A-Fa-f0-9]{32}", TMDB_API_KEY):
        logger.warning("TMDB_API_KEY format looks unusual (expected 32 hex characters).")
    # Log safely (only first 4 chars)
    logger.info("TMDB API key loaded (%s****)", TMDB_API_KEY[:4])

TMDB_BASE_URL = os.getenv("TMDB_BASE_URL", "https://api.themoviedb.org/3")
TMDB_BASE_URL = TMDB_BASE_URL.rstrip("/")
TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p"

# ---- TVMaze ----
TVMAZE_BASE_URL = os.getenv("TVMAZE_BASE_URL", "https://api.tvmaze.com")
TVMAZE_BASE_URL = TVMAZE_BASE_URL.rstrip("/")

# ---- Jikan ----
JIKAN_BASE_URL = os.getenv("JIKAN_BASE_URL", "https://api.jikan.moe/v4")
JIKAN_BASE_URL = JIKAN_BASE_URL.rstrip("/")

# ---- AniList ----
ANILIST_URL = os.getenv("ANILIST_URL", "https://graphql.anilist.co")
ANILIST_URL = ANILIST_URL.rstrip("/")

# ---- Optional: Log that all API base URLs are ready ----

logger.debug("TMDB base URL: %s", TMDB_BASE_URL)
logger.debug("TMDB image base URL: %s", TMDB_IMAGE_BASE_URL)
logger.debug("TVMaze base URL: %s", TVMAZE_BASE_URL)
logger.debug("Jikan base URL: %s", JIKAN_BASE_URL)
logger.debug("AniList URL: %s", ANILIST_URL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}

