# Generated by Django 6.0.2 on 2026-06-14 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('membership_status', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.CharField(help_text='Telegram Channel ID (Example: -1001234567890)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channel', to='coremovieshub.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime'), ('documentary', 'Documentary'), ('tvshow', 'TV Show')], default='movie', max_length=20)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_file_id', models.TextField(blank=True, null=True)),
                ('telegram_message_link', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=30)),
                ('poster', models.URLField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Telegram caption or custom notes')),
                ('file_size', models.CharField(blank=True, max_length=30)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='completed', max_length=20)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coremovieshub.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='coremovieshub.telegramchannel')),
            ],
            options={
                'verbose_name': 'Telegram Movie',
                'verbose_name_plural': 'Telegram Movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremovieshub.telegrammovie')),
            ],
        ),
        migrations.CreateModel(
            name='TMDBMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('title_normalized', models.CharField(max_length=500, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('backdrop_path', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title_normalized'], name='coremoviesh_title_n_2412a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coremovieshub.category')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremovieshub.telegrammovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['title'], name='coremoviesh_title_a6c90c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['year'], name='coremoviesh_year_476ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['quality'], name='coremoviesh_quality_2c3b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['language'], name='coremoviesh_languag_c0e726_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['content_type'], name='coremoviesh_content_bef010_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['is_featured'], name='coremoviesh_is_feat_e82fed_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['created_at'], name='coremoviesh_created_d303fc_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['slug'], name='coremoviesh_slug_a0da5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegrammovie',
            constraint=models.UniqueConstraint(fields=('telegram_message_id', 'channel'), name='unique_channel_message'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['user'], name='coremoviesh_user_id_31040a_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['movie'], name='coremoviesh_movie_i_639ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['downloaded_at'], name='coremoviesh_downloa_2d524b_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_watchlist'),
        ),
    ]
