# Generated by Django 6.0.2 on 2026-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammovie',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='tmdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
