# Generated by Django 6.0.2 on 2026-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammovie',
            name='episode_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='season_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='number_of_episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='number_of_seasons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
