# Generated by Django 6.0.2 on 2026-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='title_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
