# Generated by Django 6.0.2 on 2026-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0002_alter_tmdbmovie_title_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='original_language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
