# Generated by Django 6.0.2 on 2026-06-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0002_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('membership_status', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
