# Generated by Django 6.0.2 on 2026-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0002_telegrammovie_banner_url_telegrammovie_poster_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammovie',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='telegrammovie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='telegrammovie',
            name='tmdb_rating',
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
