# Generated by Django 6.0.2 on 2026-06-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0003_membershipverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.CharField(help_text='Telegram Channel ID (e.g. -1001234567890)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channel', to='coremovieshub.category')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('telegram_message_id', models.BigIntegerField()),
                ('telegram_file_id', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coremovieshub.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='coremovieshub.telegramchannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
