# Generated by Django 6.0.2 on 2026-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0003_tmdbmovie_original_language_tmdbmovie_original_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammovie',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Telegram Movie', 'verbose_name_plural': 'Telegram Movies'},
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='backdrop_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='genres',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='poster_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tmdbmovie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Runtime in minutes', null=True),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['tmdb_id'], name='coremoviesh_tmdb_id_d701f1_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['telegram_message_id'], name='coremoviesh_telegra_a96e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['status'], name='coremoviesh_status_9d3092_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['category'], name='coremoviesh_categor_45b721_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['channel'], name='coremoviesh_channel_67878b_idx'),
        ),
    ]
