# Generated by Django 6.0.2 on 2026-06-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0004_alter_telegrammovie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammovie',
            name='genres',
            field=models.CharField(blank=True, default='', help_text='Comma-separated genres (e.g., Action, Sci-Fi)', max_length=500),
        ),
    ]
