# Generated by Django 6.0.2 on 2026-06-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0004_telegramchannel_telegrammovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=50),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime'), ('documentary', 'Documentary')], default='movie', max_length=20),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='telegram_message_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
