# Generated by Django 6.0.2 on 2026-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0005_telegrammovie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
