# Generated by Django 6.0.2 on 2026-06-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0005_category_description_category_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='telegramchannel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='episode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='file_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='telegrammovie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='chat_id',
            field=models.CharField(help_text='Telegram Channel ID (Example: -1001234567890)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime'), ('documentary', 'Documentary'), ('tvshow', 'TV Show')], default='movie', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['title'], name='coremoviesh_title_a6c90c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['year'], name='coremoviesh_year_476ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['language'], name='coremoviesh_languag_c0e726_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['content_type'], name='coremoviesh_content_bef010_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['is_featured'], name='coremoviesh_is_feat_e82fed_idx'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremovieshub.telegrammovie'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremovieshub.telegrammovie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
