# Generated by Django 6.0.2 on 2026-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0006_tmdbmovie_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='production_companies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='production_countries',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='spoken_languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
