# Generated by Django 6.0.2 on 2026-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0006_downloadhistory_watchlist_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammovie',
            name='telegram_file_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
