# Generated by Django 6.0.2 on 2026-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0007_alter_telegrammovie_telegram_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipverification',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
