# Generated by Django 6.0.2 on 2026-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0008_membershipverification_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammovie',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
