# Generated by Django 6.0.2 on 2026-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0009_alter_telegrammovie_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['quality'], name='coremoviesh_quality_2c3b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['created_at'], name='coremoviesh_created_d303fc_idx'),
        ),
    ]
