# Generated by Django 6.0.2 on 2026-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0010_telegrammovie_coremoviesh_quality_2c3b9b_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='telegrammovie',
            constraint=models.UniqueConstraint(fields=('telegram_message_id', 'channel'), name='unique_channel_message'),
        ),
    ]
