# Generated by Django 6.0.2 on 2026-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremovieshub', '0012_telegrammovie_tmdb_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammovie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram Movie', 'verbose_name_plural': 'Telegram Movies'},
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Telegram caption or custom notes'),
        ),
        migrations.AlterField(
            model_name='telegrammovie',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='telegrammovie',
            index=models.Index(fields=['slug'], name='coremoviesh_slug_a0da5c_idx'),
        ),
    ]
